apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: #REPLACE <port; 80>
    targetPort: #REPLACE <port; 8080>
    protocol: TCP
  selector:
    app: app
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: #REPLACE <acr-name>.azurecr.io/<app-name>:<tag>
        ports:
        - containerPort: #REPLACE <port; 8080>
        envFrom:
         - configMapRef:
             name: env-variables
      imagePullSecrets:
        - name: docker-secrets