variable "app_name" {}
variable "location" {}
variable "service_principal_name" {}
variable "service_principal_password" {}
variable "service_principal_password_expiry_date" {}
variable "network_address_space" {}
variable "subnet_address_prefix" {}
variable "registry_name" {}
variable "registry_sku" {}
variable "docker_username" {}
variable "docker_email" {}
variable "aks_node_count" {}
variable "aks_vm_size" {}
variable "aks_disk_size_gb" {}
variable "ssh_key" {}